CREATE TABLE IF NOT EXISTS users (
  id    BIGINT        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name  VARCHAR(128)  NOT NULL,
  email VARCHAR(512)  NOT NULL,

  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(512) NOT NULL,
  requestor   INT          NOT NULL,
  created     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT pk_requests PRIMARY KEY (id),
  CONSTRAINT fk_requestor FOREIGN KEY (requestor) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS items (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  owner_id      BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  name          VARCHAR(128) NOT NULL,
  description   VARCHAR(512) NOT NULL,
  is_available  BOOLEAN      DEFAULT(FALSE) NOT NULL,
  request_id    BIGINT,

  CONSTRAINT pk_item PRIMARY KEY (id),
  CONSTRAINT fk_owner FOREIGN KEY (owner_id) REFERENCES users (id),
  FOREIGN KEY (request_id) REFERENCES requests (id)
);

CREATE TABLE IF NOT EXISTS booking (
  id           BIGINT     GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  start_date   TIMESTAMP  WITHOUT TIME ZONE,
  end_date     TIMESTAMP  WITHOUT TIME ZONE,
  item_id      BIGINT     NOT NULL,
  booker_id    BIGINT     NOT NULL,
  status       VARCHAR(8) NOT NULL,

  CONSTRAINT pk_booking PRIMARY KEY (id),
  CONSTRAINT fk_booking FOREIGN KEY (item_id) REFERENCES items (id),
  CONSTRAINT fk_booker FOREIGN KEY (booker_id) REFERENCES users (id)
);